# Generated by Django 3.2.18 on 2023-02-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemeet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
