# Generated by Django 3.2.18 on 2023-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemeet', '0002_alter_meeting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='ending_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
